<img onclick=bold() align=absmiddle src="pic/icon_editor_bold.gif" width="22" height="22" alt="粗体" border="0"
><img onclick=italicize() align=absmiddle src="pic/icon_editor_italicize.gif" width="23" height="22" alt="斜体" border="0"
><img onclick=underline() align=absmiddle src="pic/icon_editor_underline.gif" width="23" height="22" alt="下划线" border="0"
><img onclick=hyperlink() align=absmiddle src="pic/icon_editor_url.gif" width="22" height="22" alt="超级连接" border="0"
><img onclick=image() align=absmiddle src="pic/icon_editor_image.gif" width="23" height="22" alt="图片" border="0"
><img onclick=showcode() align=absmiddle src="pic/icon_editor_code.gif" width="22" height="22" alt="编号" border="0"
><img onclick=quote() align=absmiddle src="pic/icon_editor_quote.gif" width="23" height="22" alt="引用" border="0"
><img onclick=list() align=absmiddle src="pic/icon_editor_list.gif" width="23" height="22" alt="目录" border="0"
>
